drop table bill_data;

create table bill_data (
    file_name char(40) CHARACTER SET utf8,
    state char(2) CHARACTER SET utf8,
    phrase char(255) CHARACTER SET utf8
);

truncate table bill_data;

load data local infile '/Users/dangoldin/Dropbox/dev/web/bill-similarities/bill-temp.txt' into table bill_data fields terminated by '\t'
enclosed by ''
lines terminated by '\n'
(file_name, state, phrase);

load data local infile '/Users/dangoldin/Dropbox/dev/web/bill-similarities/bill-data-dump.txt' into table bill_data fields terminated by '\t'
enclosed by ''
lines terminated by '\n'
(file_name, state, phrase);

ALTER TABLE bill_data ADD INDEX (file_name) ;
ALTER TABLE bill_data ADD INDEX (phrase) ;
ALTER TABLE bill_data ADD INDEX (state) ;

select * from bill_data limit 100;

select count(1) from bill_data;

select phrase, count(1) as count, count(distinct(state)) as num_states
from bill_data
group by phrase
having count(1) > 1
order by count desc;

select * from bill_data
where phrase = 'liquidated damages unless client proves good faith basis';

select * from bill_data
where phrase in (
'second subsequent offense occurs within six years date',
'proves good faith basis believe underpayment compensation compliance',
'proves good faith basis believing underpayment compensation compliance',
'courts upon compensation claim independent contractor commissioner independent',
'contractor commissioner independent contractor files complaint regarding violation',
'effective date bill takes effect immediately upon enactment',
'event second subsequent offense occurs within six years',
'commissioner independent contractor files complaint regarding violation provision',
'compensation accrued six years previous commencing action whether',
'compensation civil penalties intent seek criminal penalties event',
'compensation claim independent contractor commissioner independent contractor prevails',
'compensation found due order issued client previously found',
'directing payment compensation found due order issued client',
'previous commencing action whether action instituted independent contractor',
'payment compensation found due order issued client previously',
'penalties intent seek criminal penalties event criminal penalties',
'manufacture transport disposition defacement weapons dangerous instruments appliances',
'occurs within six years date conviction prior offense',
'offense occurs within six years date conviction prior',
'client proves good faith basis believe underpayment compensation',
'client proves good faith basis believing underpayment compensation',
'civil penalties intent seek criminal penalties event criminal',
'collection back compensation civil penalties intent seek criminal',
'commencing action whether action instituted independent contractor commissioner',
'back compensation civil penalties intent seek criminal penalties',
'award collection back compensation civil penalties intent seek',
'action instituted courts upon compensation claim independent contractor',
'action instituted independent contractor commissioner independent contractor files',
'action whether action instituted independent contractor commissioner independent',
'accrued six years previous commencing action whether action',
'independent contractor commissioner independent contractor files complaint regarding',
'later last day month following month compensation earned',
'found due order issued client previously found violation',
'instituted courts upon compensation claim independent contractor commissioner',
'instituted independent contractor commissioner independent contractor files complaint',
'intent seek criminal penalties event criminal penalties sought',
'whether action instituted independent contractor commissioner independent contractor',
'years previous commencing action whether action instituted independent',
'subsequent offense occurs within six years date conviction',
'six years previous commencing action whether action instituted',
'unless client proves good faith basis believe underpayment',
'unless client proves good faith basis believing underpayment',
'upon compensation claim independent contractor commissioner independent contractor',
'val efforts break function showbillpositions bid pid var',
'val principals break case selectedtab val efforts break',
'val selectedtab selectedtab length switch selectedtab tolowercase case',
'var content billposwindow window content html loading positions',
'var content billposwindow window content html var dlg',
'var dlg billposwindow data twindow var url principalinformation',
'var item e item var selectedtab selectedtab item',
'var ndx item index switch ndx case selectedtab',
'var selectedtab selectedtab item selectedtab var ndx item',
'var selectedtab selectedtab val selectedtab selectedtab length switch',
'var tabindex var selectedtab selectedtab val selectedtab selectedtab',
'var tabstrip tabstrip data ttabstrip tabstrip select item',
'var url principalinformation pid bid bid dlg ajaxrequest',
'url dlg center open function closebillpositions var content',
'url principalinformation pid bid bid dlg ajaxrequest url',
'window content html loading positions pease wait var',
'window content html var dlg billposwindow data twindow',
'wait var dlg billposwindow data twindow var url',
'view informationmaximizeclose document ready function selecttabitem searchbutton focus',
'tabindex break case efforts tabindex break var tabstrip',
'tabindex break var tabstrip tabstrip data ttabstrip tabstrip',
'tabindex function onselecttab e var item e item',
'tabindex var selectedtab selectedtab val selectedtab selectedtab length',
'tabstrip data ttabstrip tabstrip select item tabstrip element',
'tabstrip element tabindex function onselecttab e var item',
'tabstrip select item tabstrip element tabindex function onselecttab',
'tabstrip tabstrip data ttabstrip tabstrip select item tabstrip',
'text history lobbying principalslobbying efforts bill positionsclose copyright',
'switch ndx case selectedtab val principals break case',
'switch selectedtab tolowercase case principals tabindex break case',
'ttabstrip tabstrip select item tabstrip element tabindex function',
'twindow var url principalinformation pid bid bid dlg',
'tolowercase case principals tabindex break case efforts tabindex',
'onselecttab e var item e item var selectedtab',
'open function closebillpositions var content billposwindow window content',
'ndx case selectedtab val principals break case selectedtab',
'ndx item index switch ndx case selectedtab val',
'positions pease wait var dlg billposwindow data twindow',
'positionsclose copyright government accountability board rights reserved mobile',
'principalinformation pid bid bid dlg ajaxrequest url dlg',
'principals break case selectedtab val efforts break function',
'principals tabindex break case efforts tabindex break var',
'principalslobbying efforts bill positionsclose copyright government accountability board',
'print legislative bill resolution legislative session senate bill',
'may bring legal action necessary including administrative action',
'loading positions pease wait var dlg billposwindow data',
'lobbying interests keyword select legislative session print legislative',
'lobbying principalslobbying efforts bill positionsclose copyright government accountability',
'pid bid bid dlg ajaxrequest url dlg center',
'pid var content billposwindow window content html loading',
'pease wait var dlg billposwindow data twindow var',
'mobile view informationmaximizeclose document ready function selecttabitem searchbutton',
'means device uses electronic signals create transmit receive',
'ready function selecttabitem searchbutton focus function selecttabitem var',
'reasonable attorney fees unless client proves good faith',
'reserved mobile view informationmaximizeclose document ready function selecttabitem',
'session print legislative bill resolution legislative session senate',
'showbillpositions bid pid var content billposwindow window content',
'rights reserved mobile view informationmaximizeclose document ready function',
'searchbutton focus function selecttabitem var tabindex var selectedtab',
'select item tabstrip element tabindex function onselecttab e',
'select legislative session print legislative bill resolution legislative',
'selectedtab item selectedtab var ndx item index switch',
'selectedtab length switch selectedtab tolowercase case principals tabindex',
'selectedtab selectedtab item selectedtab var ndx item index',
'selectedtab selectedtab length switch selectedtab tolowercase case principals',
'selectedtab selectedtab val selectedtab selectedtab length switch selectedtab',
'selectedtab tolowercase case principals tabindex break case efforts',
'selectedtab val efforts break function showbillpositions bid pid',
'selectedtab val principals break case selectedtab val efforts',
'selectedtab val selectedtab selectedtab length switch selectedtab tolowercase',
'selectedtab var ndx item index switch ndx case',
'selecttabitem searchbutton focus function selecttabitem var tabindex var',
'selecttabitem var tabindex var selectedtab selectedtab val selectedtab',
'device means device uses electronic signals create transmit',
'device uses electronic signals create transmit receive information',
'efforts bill positionsclose copyright government accountability board rights',
'efforts break function showbillpositions bid pid var content',
'efforts tabindex break var tabstrip tabstrip data ttabstrip',
'electronic communications device means device uses electronic signals',
'element tabindex function onselecttab e var item e',
'e item var selectedtab selectedtab item selectedtab var',
'e var item e item var selectedtab selectedtab',
'dlg ajaxrequest url dlg center open function closebillpositions',
'dlg billposwindow data twindow var url principalinformation pid',
'dlg center open function closebillpositions var content billposwindow',
'document ready function selecttabitem searchbutton focus function selecttabitem',
'contractor reasonable attorney fees unless client proves good',
'data ttabstrip tabstrip select item tabstrip element tabindex',
'data twindow var url principalinformation pid bid bid',
'fees unless client proves good faith basis believe',
'communications device means device uses electronic signals create',
'content billposwindow window content html loading positions pease',
'content billposwindow window content html var dlg billposwindow',
'content html loading positions pease wait var dlg',
'content html var dlg billposwindow data twindow dlg',
'commissioner may bring legal action necessary including administrative',
'focus function selecttabitem var tabindex var selectedtab selectedtab',
'keyword select legislative session print legislative bill resolution',
'independent contractor may file commissioner complaint regarding violation',
'independent contractor reasonable attorney fees unless client proves',
'index switch ndx case selectedtab val principals break',
'length switch selectedtab tolowercase case principals tabindex break',
'legislative bill resolution legislative session senate bill relating',
'legislative session print legislative bill resolution legislative session',
'html loading positions pease wait var dlg billposwindow',
'html var dlg billposwindow data twindow dlg close',
'history lobbying principalslobbying efforts bill positionsclose copyright government',
'function closebillpositions var content billposwindow window content html',
'function onselecttab e var item e item var',
'function selecttabitem searchbutton focus function selecttabitem var tabindex',
'function selecttabitem var tabindex var selectedtab selectedtab val',
'function showbillpositions bid pid var content billposwindow window',
'item e item var selectedtab selectedtab item selectedtab',
'item index switch ndx case selectedtab val principals',
'item selectedtab var ndx item index switch ndx',
'item tabstrip element tabindex function onselecttab e var',
'item var selectedtab selectedtab item selectedtab var ndx',
'informationmaximizeclose document ready function selecttabitem searchbutton focus function',
'interests keyword select legislative session print legislative bill',
'accountability board rights reserved mobile view informationmaximizeclose document',
'bear burden proving complaining independent contractor paid compensation',
'attorney fees unless client proves good faith basis',
'bill text history lobbying principalslobbying efforts bill positionsclose',
'bid bid dlg ajaxrequest url dlg center open',
'bid dlg ajaxrequest url dlg center open function',
'bid pid var content billposwindow window content html',
'board rights reserved mobile view informationmaximizeclose document ready',
'bill positionsclose copyright government accountability board rights reserved',
'break case efforts tabindex break var tabstrip tabstrip',
'break case selectedtab val efforts break function showbillpositions',
'break function showbillpositions bid pid var content billposwindow',
'break var tabstrip tabstrip data ttabstrip tabstrip select',
'billposwindow data twindow var url principalinformation pid bid',
'billposwindow window content html loading positions pease wait',
'billposwindow window content html var dlg billposwindow data',
'closebillpositions var content billposwindow window content html var',
'ajaxrequest url dlg center open function closebillpositions var',
'allow independent contractor reasonable attorney fees unless client',
'case principals tabindex break case efforts tabindex break',
'case selectedtab val efforts break function showbillpositions bid',
'case selectedtab val principals break case selectedtab val',
'center open function closebillpositions var content billposwindow window',
'case efforts tabindex break var tabstrip tabstrip data',
'appointed state giving notice appointing court intent register',
'appointment except prohibited laws state including maintaining actions',
'senator byron m baer open public meetings act',
'section d court shall issue order provisionally granting',
'prohibited laws state including maintaining actions proceedings state',
'promote uniformity law respect subject matter among states',
'upon nonresident parties b court state may grant',
'uniformity law respect subject matter among states enact',
'transfer proceeding would contrary interests incapacitated protected person',
'state giving notice appointing court intent register may',
'need promote uniformity law respect subject matter among',
'nonresident parties b court state may grant relief',
'order appointment except prohibited laws state including maintaining',
'parties b court state may grant relief available',
'person required notified proceeding court shall hold hearing',
'place designed ordinarily used regular sleeping accommodation human',
'proceeding would contrary interests incapacitated protected person guardian',
'imposed upon nonresident parties b court state may',
'given need promote uniformity law respect subject matter',
'giving notice appointing court intent register may register',
'designed ordinarily used regular sleeping accommodation human beings',
'except prohibited laws state including maintaining actions proceedings',
'court jurisdiction make appointment reason provisional order transfer',
'disclose user name password means accessing personal account',
'consumer price index urban wage earners clerical workers',
'federal special supplemental nutrition program women infants children',
'special supplemental nutrition program women infants children wic',
'user name password means accessing personal account service',
'supplemental nutrition program women infants children wic particular',
'publicly privately operated shelter designed provide temporary living',
'nutrition program women infants children wic particular site',
'operated shelter designed provide temporary living accommodations including',
'privately operated shelter designed provide temporary living accommodations',
'participate federal special supplemental nutrition program women infants',
'means accessing personal account service electronic communications device',
'otherwise divulged made public disclose identity person relate',
'paid compensation earned later last day month following',
'password means accessing personal account service electronic communications',
'owned manufactured commercially privately state remains exclusively within',
'name password means accessing personal account service electronic',
'price index urban wage earners clerical workers cpi',
'case conference potential civil criminal penalties collection procedures',
'ammunition owned manufactured commercially privately state remains exclusively',
'amount liquidated damages unless client proves good faith',
'addition directing payment compensation found due order issued',
'accessory ammunition owned manufactured commercially privately state remains',
'bank savings bank savings loan association credit union',
'client agree date payment compensation earned independent contractor',
'compensation earned later last day month following month',
'damages unless client proves good faith basis believing',
'earned later last day month following month compensation',
'energy environmental design leed green building rating system',
'contractor client agree date payment compensation earned independent',
'states environmental protection agency united states department energy',
'united states environmental protection agency united states department',
'investigation case conference potential civil criminal penalties collection',
'firearm accessory ammunition owned manufactured commercially privately state',
'including investigation case conference potential civil criminal penalties',
'independent contractor client agree date payment compensation earned',
'index urban wage earners clerical workers cpi w',
'limited partnership limited liability partnership limited liability company',
'liquidated damages unless client proves good faith basis',
'leadership energy environmental design leed green building rating',
'services necessary allow qualifying senior family member maintained',
'resolution legislative session senate bill relating prohibiting use',
'release extended release form whether combined drug substances',
'release form whether combined drug substances form single',
'remove barriers educational success imposed children military families',
'relating prohibiting use telephone automatic dialing announcing devices',
'senate bill relating prohibiting use telephone automatic dialing',
'section section section section section section section section',
'sentence imprisonment less one year five years fine',
'session senate bill relating prohibiting use telephone automatic',
'severe pain conditions whether immediate release extended release',
'providing penalty bill text history lobbying principalslobbying efforts',
'prohibiting use telephone automatic dialing announcing devices political',
'telephone automatic dialing announcing devices political messages providing',
'use telephone automatic dialing announcing devices political messages',
'subject federal law federal regulation including registration authority',
'treat moderate severe pain conditions whether immediate release',
'whether immediate release extended release form whether combined',
'would contrary federal regulations would jeopardize federal financial',
'claim respect reduction tampering abuse abuse potential time',
'class prescribed treat moderate severe pain conditions whether',
'automatic dialing announcing devices political messages providing penalty',
'bear labeling claim respect reduction tampering abuse abuse',
'advertisement mail rebate required achieve lower net price',
'bill relating prohibiting use telephone automatic dialing announcing',
'bill resolution legislative session senate bill relating prohibiting',
'announcing devices political messages providing penalty bill text',
'arising connection traffic accident record accident applicant fault',
'political messages providing penalty bill text history lobbying',
'prescribed treat moderate severe pain conditions whether immediate',
'pain conditions whether immediate release extended release form',
'moderate severe pain conditions whether immediate release extended',
'messages providing penalty bill text history lobbying principalslobbying',
'penalty bill text history lobbying principalslobbying efforts bill',
'manufactured without inclusion significant parts imported another state',
'legislative session senate bill relating prohibiting use telephone',
'labeling claim respect reduction tampering abuse abuse potential',
'immediate release extended release form whether combined drug',
'increase consumer price index urban wage earners clerical',
'hydroxymethyl dimethyl methyloctan yl tetrahydrobenzo c chromen ol',
'contrary federal regulations would jeopardize federal financial participation',
'dodd frank wall street reform consumer protection act',
'drug class prescribed treat moderate severe pain conditions',
'devices political messages providing penalty bill text history',
'dialing announcing devices political messages providing penalty bill',
'conditions whether immediate release extended release form whether',
'extended release form whether combined drug substances form',
'exempt federal income taxation section c internal revenue',
'federal income taxation section c internal revenue code'
);

select state, count(distinct(file_name)) as num_files
from bill_data
group by state;